name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |

          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:latest . -t ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:${COMMIT_HASH} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:${COMMIT_HASH}

      - name: Deploy Docker container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DIGITALOCEAN_VM_IP }}
          username: ${{ secrets.DIGITALOCEAN_VM_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:latest
            docker stop my-reactjs-container || true
            docker rm my-reactjs-container || true
            docker run -d --name my-reactjs-container \
                -p 80:80 -p 443:443 \
                -v /etc/letsencrypt/live/adnansabovic.online:/etc/letsencrypt/live/adnansabovic.online \
                -v /etc/letsencrypt/archive/adnansabovic.online:/etc/letsencrypt/archive/adnansabovic.online \
                ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-app:latest


